version: '3'

services:
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./works:/app/works"
      - "./.jupyter:/root/.jupyter"
    ports:
      - 10000:8888
    command: jupyter-lab --port=8888 --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
